"""change date to date_sent

Revision ID: 9715aed0fbe8
Revises: a60795c2571d
Create Date: 2025-12-31 06:05:40.751972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9715aed0fbe8'
down_revision: Union[str, Sequence[str], None] = 'a60795c2571d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('date_sent', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('emails', 'from_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('emails', 'to_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_emails_date'), table_name='emails')
    op.drop_index(op.f('ix_emails_thread_date'), table_name='emails')
    op.create_index('ix_emails_thread_date', 'emails', ['thread_id', 'date_sent'], unique=False)
    op.create_index(op.f('ix_emails_date_sent'), 'emails', ['date_sent'], unique=False)
    op.drop_column('emails', 'date')
    op.alter_column('sync_state', 'last_started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('sync_state', 'last_finished_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index('ix_sync_state_history_id', 'sync_state', ['history_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sync_state_history_id', table_name='sync_state')
    op.alter_column('sync_state', 'last_finished_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('sync_state', 'last_started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('emails', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_emails_date_sent'), table_name='emails')
    op.drop_index('ix_emails_thread_date', table_name='emails')
    op.create_index(op.f('ix_emails_thread_date'), 'emails', ['thread_id', 'date'], unique=False)
    op.create_index(op.f('ix_emails_date'), 'emails', ['date'], unique=False)
    op.alter_column('emails', 'to_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('emails', 'from_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('emails', 'date_sent')
    # ### end Alembic commands ###
