"""empty message

Revision ID: db1049dfd1f1
Revises: c3cd0003c76a
Create Date: 2025-12-21 09:57:05.529347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db1049dfd1f1'
down_revision: Union[str, Sequence[str], None] = 'c3cd0003c76a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emails', 'predicted_labels',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('emails', 'applied_labels',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_emails_gmail_id'), table_name='emails')
    op.drop_index(op.f('idx_emails_inbox'), table_name='emails')
    op.drop_index(op.f('idx_predicted_labels'), table_name='emails', postgresql_using='gin')
    op.drop_index(op.f('idx_training_label'), table_name='training_samples')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_training_label'), 'training_samples', ['label_id'], unique=False)
    op.create_index(op.f('idx_predicted_labels'), 'emails', ['predicted_labels'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_emails_inbox'), 'emails', ['in_inbox'], unique=False)
    op.create_index(op.f('idx_emails_gmail_id'), 'emails', ['gmail_id'], unique=False)
    op.alter_column('emails', 'applied_labels',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('emails', 'predicted_labels',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
