"""add performance indexes

Revision ID: f33c4b7feb88
Revises: 195926cd937f
Create Date: 2025-12-24 12:36:42.012319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f33c4b7feb88'
down_revision: Union[str, Sequence[str], None] = '195926cd937f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_emails_date'), 'emails', ['date'], unique=False)
    op.create_index('ix_emails_thread_date', 'emails', ['thread_id', 'date'], unique=False)
    op.create_index(op.f('ix_emails_thread_id'), 'emails', ['thread_id'], unique=False)
    op.alter_column('labels', 'email_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_labels_email_id'), 'labels', ['email_id'], unique=False)
    op.create_index(op.f('ix_labels_name'), 'labels', ['name'], unique=False)
    op.drop_constraint(op.f('labels_email_id_fkey'), 'labels', type_='foreignkey')
    op.create_foreign_key(None, 'labels', 'emails', ['email_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labels', type_='foreignkey')
    op.create_foreign_key(op.f('labels_email_id_fkey'), 'labels', 'emails', ['email_id'], ['id'])
    op.drop_index(op.f('ix_labels_name'), table_name='labels')
    op.drop_index(op.f('ix_labels_email_id'), table_name='labels')
    op.alter_column('labels', 'email_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_emails_thread_id'), table_name='emails')
    op.drop_index('ix_emails_thread_date', table_name='emails')
    op.drop_index(op.f('ix_emails_date'), table_name='emails')
    # ### end Alembic commands ###
